### PR TITLE
Mmate91 getting started

### PR DESCRIPTION
**Pull request by mmate91**

### CODE REVIEW

**Comment by erikzhang** [comment]
So, you break the original structure of the document, and make it a little strange, I think....

**Comment by mmate91** [comment]
You're right, i updated the file, tried to keep the original structure.

**Comment by erikzhang** [comment]
The structure is fine now.
In your page, I didn't find the step to install the plugin "NeoContractPlugin". Is there any reason not to use the plugin?

**Comment by mmate91** [comment]
I just wanted to demonstrate that how we can build up with basic references. This isn't the easiest way, shows the references. Would you like me to create a tutorial with the plug-in instead?

**Comment by mmate91** [comment]
I think, the getting started.md that you updated a few hours ago are good now, but still we still need to update some images in there. I will concentrate on them and close this request.

**Pull request closed without merging**
