### PR TITLE
Initial Japanese translation

### PR DESCRIPTION
**Pull request by canesin**
From slack community.

### CODE REVIEW

**Comment by CJSS** [comment]
*Japanese

**Comment by erikzhang** [comment]
Who can review the Japanese translation? Which one is better? This or #52 ?

**Comment by canesin** [comment]
@erikzhang this is a lot bigger, this include the smart contract documentation tutorials. The other is just the index.md, I would propose accept this one first and rebase the other on top of this to refine the index.md

**Comment by anfn101** [comment]
Agreed, this one includes a lot more, so it would be easier to use this one. This was also worked on by at least 3 Japanese speaking translators, so I can vouch for its accuracy and quality.

**Comment by anfn101** [comment]
Conflict resolved.

**Comment by erikzhang** [comment]
@anfn101 Good! And we need a toc.yml in ja-jp directory.

**Comment by erikzhang** [comment]
And it seems you removed the ko-kr from root toc.yml?

**Comment by anfn101** [comment]
Yes, I will add it in later when I push the Korean translations.

**Comment by erikzhang** [comment]
But the Korean translations are already in.
https://github.com/neo-project/docs/tree/master/ko-kr

**Comment by anfn101** [comment]
OK I wasn't aware that someone already pushed that to main... I'll fix that then

**Comment by anfn101** [comment]
We'll get the JP toc up very soon

**Comment by anfn101** [comment]
JP toc.yml has been added. That should be all that is needed for merge...

**Comment by erikzhang** [comment]
It seems some pages are in the toc but not in the directory. Please remove those nonexistent pages from toc. Otherwise, visitors will get a 404 error if they click the links.

**Comment by anfn101** [comment]
Okay, removed the nonexistent references. Please check. If that is all that is needed, feel free to merge.

**Comment by anfn101** [comment]
Added some additional translations: white-paper, api, fw, introduction, and updated the toc.yml to account for those as well. @erikzhang

**Pull request merged**
