### PR TITLE
update english

### PR DESCRIPTION
**Pull request by canesin**
Update english up to date with develop from COZ.

### CODE REVIEW

**Comment by canesin** [comment]
Better ?

**Comment by erikzhang** [comment]
It's better now.

**Comment by CJSS** [comment]
I created a pull on your branch with a suggested rewording, which is just a suggestion.

The English still isn't quite right, for example:
During the first 2 million blocks (approximately one year)...
the second year (blocks from 2 to 4 million)

The item in brackets should be consistent - so both the number of years, or both the number of blocks, should be inside the brackets.

**Comment by canesin** [comment]
good to go.

**Comment by erikzhang** [comment]
@canesin please merge this pr when you think that it's ready.

**Pull request merged**
