### PR TITLE
How to request and access TEST NEO and GAS

### PR DESCRIPTION
**Pull request by fergaljos**
Provide detailed instructions for developers new to NEO how to request and access NEO and GAS on the TESTNET.

### CODE REVIEW

**Comment by fergaljos** [comment]
Is it not preferred to decouple the detail of how a developer new to NEO can recover GAS and NEO using multi-sig addresses from other details about the testnet by making it as a separate document?

**Comment by Celia18305** [comment]
@fergaljos Because it is closely related to testnet and actually a important information for developers to use testnet (Thanks for your contribution), I think it is more appropriate to add it to the same document as a complete tutorial.

**Comment by fergaljos** [comment]
@Celia18305  and @Ray-77,
Changes made. I deleted the propose new page and merged the content into the testnet.mp page. Kind regards.

**Comment by jonatanblockchain** [comment]
@fergaljos @Celia18305 Can you add a note on Step-3 to indicate that before create the mutisig contract the wallet must be on sync?

**Pull request merged**
