### PR TITLE
Tagalog / Filipino Translations

### PR DESCRIPTION
**Pull request by severinolorillajr**
To whom it may concern:

We are a group of Filipino translators and would really love to help you translate your documentations to our local language. We are active contributors at CrowdIn and now here at GitHub as well, and our main focus is to contribute to any open-source projects.

One of our latest project was this: https://github.com/progit2-tl/progit2
You can view the production site here: https://git-scm.com/book/tl/v2

This PR is just a copy of the EN folder. 
If you are okay with having us translate these documents for you, may I also suggest to use my forked repo for Tagalog translations? Our usual process is that we also have review and proofreading, so if there are new contributors, hope you can point them to this forked repo so we can ensure that every contribution will undergo a review process, that way we can ensure that the translations are of good quality.

Then, maybe twice a week, I will just create a PR to update your main repository.
Let me know if this works for you.

And by the way, you can contact me at severinolorillajr@gmail.com if you need further info.

### CODE REVIEW

**Comment by Celia18305** [comment]
@severinolorillajr Thank you for contacting us. We definitely expect our doc to be translated into more languages.  I just have a few questions: Is there additional support you need from us? Is there any charge for this translation? Thanks!

**Comment by severinolorillajr** [comment]
Hi @Celia18305 ,

Nope there is no charges for our services.
Our only request is that you can merge our work to your project.
And hopefully soon you will be able to make use of them.

We also aim to provide quality translations, so we created a group that will contribute, review and proofread everything to make sure that the quality is good for production. And in line with this, we would like to ask that if there are other contributors for our language, hope you can bring them to us instead of directly forking your project.

So our process will be, I will create a fork of your project, with the tl folders. And my contributors will work on my branch.  I will just make a PR to your project twice a week for updates from and to your main repository.

Let me know if this works for you or if you need anything else to get started.

Thanks.

**Comment by Celia18305** [comment]
@severinolorillajr Your work flow sounds great and yes it works for us. We really appreciate your group's contribution for making NEO doc better. Going forward if there are new Filipino translators I will point them to your repo.

**Comment by severinolorillajr** [comment]
Cool.
Let me know when we can merge this or if you need something from us.
After merging, I'll create a new fork to stage our updates for Filipino/Tagalog Translations.
Thanks.

**Comment by Celia18305** [comment]
You can start any time.
Cheers.

**Comment by severinolorillajr** [comment]
oh nice.
I need the tl folders on your main repo please.. so I can fork a new one with the translatable files.
Then we can start right away. Thanks for the trust @Celia18305 .
Cheers!

**Comment by Celia18305** [comment]
Sorry, I forgot the files you are requesting.. Now I have merged them. You can start on them once available.

**Comment by severinolorillajr** [comment]
Thanks @Celia18305 .
FYI, we will be using this as our stage repo.
https://github.com/neo-tl/docs
And will just make a PR when we have updates for you.
Thanks.

**Pull request merged**
