### PR TITLE
delete the old white-paper

### PR DESCRIPTION
**Pull request by anfn101**
Old, outdated, no longer in effect

### CODE REVIEW

**Comment by anfn101** [comment]
It's not in other languages. I never had them translate it.

**Comment by totalvm** [comment]
move the spanish one from white-paper.md to index.md?

**Comment by anfn101** [comment]
On it...

**Comment by canesin** [comment]
@totalvm , please look at the code before.. the spanish already has a index.md that is a proper translation..

**Comment by anfn101** [comment]
Removed as well...

**Pull request merged**
