### PR TITLE
Rebrand to NEO (Zh-cn)

### PR DESCRIPTION
**Pull request by mgao6767**
Rebrand to NEO.

### CODE REVIEW

**Comment by canesin** [comment]
#49 does re-brand for CN also.. I will rebase that and re PR to accelerate the process, after that we can see if this enhances the rebrand.

**Comment by mgao6767** [comment]
Yeah sure. Sorry didn't notice that Zh-cn. I can wait till that merged and keep on editing docs.

**Comment by canesin** [comment]
@mgao6767 please rebase and take a look if your PR adds to the rebrand.

**Comment by mgao6767** [comment]
@canesin Saw that merged PR. Really good work. I think the only difference is the name of neo directory, I changed it to Neo so as to make it consistent. This PR can be closed if you think that's unnecessary. Or do you prefer I change it for all languages?

**Comment by canesin** [comment]
Just rebase in the branch you are submitting from and we can see what it adds

**Pull request closed without merging**
