### PR TITLE
NEO Rebrand

### PR DESCRIPTION
**Pull request by CJSS**

### CODE REVIEW

**Comment by erikzhang** [comment]
There is no file named "NeoUI.exe". It's "neo-gui.exe" instead.

**Comment by CJSS** [comment]
Updated.
Also found some extra mentions of the previous brand.

**Comment by erikzhang** [comment]
Good job! I will merge this big PR after you correct the mistakes above.

**Comment by CJSS** [comment]
Are you changing the file extensions from .avm? Are you going to use .nvm or something else?

**Comment by erikzhang** [comment]
We will use both .avm and .nvm to make it compatible with old files.

**Comment by canesin** [comment]
@CJSS there was the simpler PR fixing the white-paper (that you contributed to), since you are also changing the white-paper in this PR you will need to rebase it.

**Comment by canesin** [comment]
@erikzhang I'm closing this since @CJSS is taking some time, I don't want to lose his great work so I will create a new PR from a fork and fix the conflicts.

**Comment by erikzhang** [comment]
This PR has been ported to #65

**Pull request closed without merging**
