### PR TITLE
Renaming things from StorageContex to StorageContext

### PR DESCRIPTION
**Pull request by anfn101**
Fix to storagecontext.md instead of storagecontex.md

### CODE REVIEW

**Comment by anfn101** [comment]
Update everything in English and Chinese folders from StorageContex to StorageContext.

**Comment by erikzhang** [comment]
Is it ready to be merged? @anfn101

**Comment by anfn101** [comment]
Yes

**Comment by anfn101** [comment]
I think I've found everything, it is ready for merge @erikzhang

**Pull request merged**
