### PR TITLE
Initial Dutch translation

### PR DESCRIPTION
**Pull request by jhepkema**
I'm going to translate this to Dutch.

### CODE REVIEW

**Comment by jhepkema** [comment]
@revett @totalvm 
Everything in the map `/node` is done and can be reviewed. Right now I'm working on getting everything in `/sc` translated.

**Comment by jhepkema** [comment]
I don't know how to rebase my repository properly, I'm doing everything using the GitHub website. If there are any inconsistensies with recent updates to the master branch, please just say which files it involves and I will translate those later on in a seperate PR from a fresh fork.

**Comment by jhepkema** [comment]
Also @shakilmia what are you trying to do? :)

**Comment by shakilmia** [comment]
nothing sir actually I don't understand

**Comment by jhepkema** [comment]
@shakilmia okay no problem, if you want to learn more about GitHub and how it works, go read [this](https://guides.github.com/activities/hello-world/) ;)

**Comment by canesin** [comment]
@jhepkema I think there is no need for a full rebase since translations are contained... since I don't understand dutch will wait for @totalvm input on this one.

**Comment by jhepkema** [comment]
@canesin Okay, that makes sense. Thanks for the reply

**Comment by jhepkema** [comment]
I did not translate the whitepaper in /node, since it has been translated already in #108.

**Comment by jhepkema** [comment]
@totalvm did the invitation come through? :)

**Comment by totalvm** [comment]
@jhepkema yes I got it, just have been very busy. I'll try and see if I can finish up this PR

**Comment by jhepkema** [comment]
Hoped so :yum:

**Pull request merged**
